keys: 
  - &w4cbe 21E16B8D2EE875306A6C9968D83077B99F8C6643
  - &donnager 896b4788b80f66b7e7e889bf325e26456917a994
  - &hermes 5eccf726c3412df9ee29cbcb0e579da7b919b794
creation_rules:
  - path_regex: secrets/global.sops.yaml$
    key_groups:
    - pgp:
      - *w4cbe
      - *donnager
      - *hermes
  - path_regex: secrets/hermes.sops.yaml$
    key_groups:
    - pgp:
      - *w4cbe
      - *hermes