keys:
  - &admin_w4cbe 21E16B8D2EE875306A6C9968D83077B99F8C6643
  - &host_donnager age1jmj0p55rffz43a3jae2c56nyc7zv5jcp5g65073gr45xzt7vqsjqguxcvm
  - &host_hermes age17l9awkletg9m57n2nz43l4rzz6n5cfa3xqv5j3khaxue3wasgsssya5lkm
  - &host_bob age1fzl9875uxced4g3xz44warhxfvs8zk2e9w2w52evrlksaexz7dasxh743r
creation_rules:
  - path_regex: secrets/donnager.yaml$
    key_groups:
    - pgp:
      - *admin_w4cbe
      age:
      - *host_donnager
  - path_regex: secrets/hermes.yaml$
    key_groups:
    - pgp:
      - *admin_w4cbe
      age:
      - *host_hermes
  - path_regex: secrets/bob.yaml$
    key_groups:
    - pgp:
      - *admin_w4cbe
      age:
      - *host_bob