keys:
  - &admin_w4cbe 21E16B8D2EE875306A6C9968D83077B99F8C
  - &host_donnager 896b4788b80f66b7e7e889bf325e26456917a994
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *admin_w4cbe
      - *host_donnager
  - path_regex: secrets/users/w4cbe/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *admin_w4cbe
      - *host_donnager


